# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "queencheck"
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sho Kusano"]
  s.date = "2012-02-02"
  s.description = "QueenCheck is random test library. Inspired by QuickCheck library in Haskell."
  s.email = "rosylilly@aduca.org"
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".rspec",
    ".rvmrc",
    ".travis.yml",
    "Gemfile",
    "Guardfile",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "lib/queencheck.rb",
    "lib/queencheck/arbitrary.rb",
    "lib/queencheck/array.rb",
    "lib/queencheck/boolean.rb",
    "lib/queencheck/config.rb",
    "lib/queencheck/core.rb",
    "lib/queencheck/elements_of.rb",
    "lib/queencheck/float.rb",
    "lib/queencheck/integer.rb",
    "lib/queencheck/string.rb",
    "queencheck.gemspec",
    "spec/queencheck/arbitrary_spec.rb",
    "spec/queencheck/core_spec.rb",
    "spec/queencheck/elements_of_spec.rb",
    "spec/queencheck/integer_spec.rb",
    "spec/queencheck/string_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "https://github.com/rosylilly/QueenCheck"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "like haskell's QuickCheck"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, [">= 1.8.3"])
      s.add_development_dependency(%q<rake>, [">= 0.9.2.2"])
      s.add_development_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_development_dependency(%q<fuubar>, [">= 0.0.6"])
      s.add_development_dependency(%q<growl>, [">= 1.0.3"])
      s.add_development_dependency(%q<spork>, [">= 0.9.0.rc9"])
      s.add_development_dependency(%q<rb-fsevent>, [">= 0.9.0"])
      s.add_development_dependency(%q<guard-spork>, [">= 0.5.1"])
      s.add_development_dependency(%q<guard-rspec>, [">= 0.6.0"])
      s.add_development_dependency(%q<guard-bundler>, [">= 0.1.3"])
      s.add_development_dependency(%q<guard-yard>, [">= 1.0.2"])
      s.add_development_dependency(%q<yard>, [">= 0.7.4"])
      s.add_development_dependency(%q<yard-tomdoc>, [">= 0.3.0"])
    else
      s.add_dependency(%q<jeweler>, [">= 1.8.3"])
      s.add_dependency(%q<rake>, [">= 0.9.2.2"])
      s.add_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_dependency(%q<fuubar>, [">= 0.0.6"])
      s.add_dependency(%q<growl>, [">= 1.0.3"])
      s.add_dependency(%q<spork>, [">= 0.9.0.rc9"])
      s.add_dependency(%q<rb-fsevent>, [">= 0.9.0"])
      s.add_dependency(%q<guard-spork>, [">= 0.5.1"])
      s.add_dependency(%q<guard-rspec>, [">= 0.6.0"])
      s.add_dependency(%q<guard-bundler>, [">= 0.1.3"])
      s.add_dependency(%q<guard-yard>, [">= 1.0.2"])
      s.add_dependency(%q<yard>, [">= 0.7.4"])
      s.add_dependency(%q<yard-tomdoc>, [">= 0.3.0"])
    end
  else
    s.add_dependency(%q<jeweler>, [">= 1.8.3"])
    s.add_dependency(%q<rake>, [">= 0.9.2.2"])
    s.add_dependency(%q<rspec>, [">= 2.8.0"])
    s.add_dependency(%q<fuubar>, [">= 0.0.6"])
    s.add_dependency(%q<growl>, [">= 1.0.3"])
    s.add_dependency(%q<spork>, [">= 0.9.0.rc9"])
    s.add_dependency(%q<rb-fsevent>, [">= 0.9.0"])
    s.add_dependency(%q<guard-spork>, [">= 0.5.1"])
    s.add_dependency(%q<guard-rspec>, [">= 0.6.0"])
    s.add_dependency(%q<guard-bundler>, [">= 0.1.3"])
    s.add_dependency(%q<guard-yard>, [">= 1.0.2"])
    s.add_dependency(%q<yard>, [">= 0.7.4"])
    s.add_dependency(%q<yard-tomdoc>, [">= 0.3.0"])
  end
end

